name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Mis à jour pour correspondre à votre environnement Azure
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Installation explicite de pytest
        pip install -r requirements.txt
        pip list  # Vérification des packages installés
    
    - name: Run unit tests
      run: |
        python -m pytest test.py -v
        
    - name: Start Flask application
      run: |
        python app.py &
        sleep 5
        
    - name: Run API tests
      run: |
        curl http://localhost:5000/health || exit 1  # Test basique de santé

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Arultharan'  # Nom de votre application Azure
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .  # Déploie le contenu du répertoire actuel